{
 "title": "Meter Readings",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Meter Data",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", \"VR\", \"VB\", \"VY\", \"VN\", \"IR\", \"IB\", \"IY\", \"IN\", \"QR\", \"QB\", \"QY\", \"QN\", \"KR\", \"KB\", \"KY\", \"KN\", \"HZ\" FROM meterdata LIMIT 50 "
    }
   ]
  },
  { "title": "Frequency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Frequency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"HZ\" FROM meterdata order by time desc limit 1"
    }
   ]
  },
  { "title": "Active Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Active Power KR (kt1)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"KR\" FROM meterdata order by time desc limit 1"
    }
   ]
  },
  {
   "title": "Active Power KB (kt2)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"KB\" FROM meterdata order by time desc limit 1"
    }
   ]
  },
  {
   "title": "Active Power KY (kt3)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"KY\" FROM meterdata order by time desc limit 1"
    }
   ]
  },
  {
   "title": "Active Power (kt)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"KN\" FROM meterdata order by time desc limit 1"
    }
   ]
  },
  { "title": "Power Factor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Power Factor QR (Q1)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "kvoltamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"QR\" FROM meterdata order by time desc limit 1"
    }
   ]
  },
  {
   "title": "Power Factor QB (Q2)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "kvoltamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"QB\" FROM meterdata order by time desc limit 1"
    }
   ]
  },
  {
   "title": "Power Factor QY (Q3)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "kvoltamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"QY\" FROM meterdata order by time desc limit 1"
    }
   ]
  },
  {
   "title": "Average Power Factor (QA)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "kvoltamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"QN\" FROM meterdata order by time desc limit 1"
    }
   ]
  },
  { "title": "Ampere", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Line Current IR (L1)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"IR\" FROM meterdata order by time desc limit 1"
    }
   ]
  },
  {
   "title": "Line Current IB (L2)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"IB\" FROM meterdata order by time desc limit 1"
    }
   ]
  },
  {
   "title": "Line Current IY (L3)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"IY\" FROM meterdata order by time desc limit 1"
    }
   ]
  },
  {
   "title": "Neutral LLine Current (IN)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"IN\" FROM meterdata order by time desc limit 1"
    }
   ]
  },
  { "title": "Voltage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Voltage VR (V1)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"VR\" FROM meterdata order by time desc limit 1"
    }
   ]
  },
  {
   "title": "Voltage VB(V2)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"VB\" FROM meterdata order by time desc limit 1"
    }
   ]
  },
  {
   "title": "Voltage VY (V3)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"VY\" FROM meterdata order by time desc limit 1"
    }
   ]
  },
  {
   "title": "Average Voltage (VN) ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"VN\" FROM meterdata order by time desc limit 1"
    }
   ]
  }
 ]
}