{
 "title": "My Kafka dashboard",
 "time": { "from": "2024-02-20T06:34:11.621Z", "to": "2024-02-20T12:34:11.621Z" },
 "panels": [
  {
   "title": "Partitions Leader Per Broker",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kafka_cluster_partition_replicascount{job=~\"kafka\", topic=~\"demoemo|docker|kafka\"}"
    }
   ]
  },
  {
   "title": "Zookeepers Online",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount{job=~\"kafka\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Brokers Online",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(job) (kafka_server_sessionexpirelistener_zookeepersyncconnects_total{job=\"kafka\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes In / Out Per Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "Bps", "label": "In (-) / Out (+)" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (rate(kafka_server_brokertopicmetrics_bytesout_total{instance=~\"kafka1:9101|kafka2:9102|kafka3:9103 \", job=\"kafka\", topic=~\"demoemo|docker|kafka|kafka1\"}[2m]))",
     "legendFormat": "Bytes Out [{{instance}}]"
    },
    {
     "expr": "sum by(instance) (rate(kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka\", instance=~\"kafka1:9101|kafka2:9102|kafka3:9103\", topic=~\"demoemo|docker|kafka|kafka1\"}[2m]))",
     "legendFormat": "Bytes In [{{instance}}]"
    }
   ]
  },
  {
   "title": "Topic Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(job) (kafka_controller_kafkacontroller_globaltopiccount{job=\"kafka\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Online Partitons",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount{job=~\"kafka\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages In Per Broker",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(topic) (increase(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\", topic=~\"docker|kafka1\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Broker",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(topic) (kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka\", topic=~\"docker|kafka1\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Broker",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(topic) (increase(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka\", topic=~\"docker|demoemo|kafka|kafka1\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance) (increase(kafka_server_brokertopicmetrics_messagesin_total{topic!=\"__consumer_offsets\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum by(topic) (kafka_server_brokertopicmetrics_bytesin_total{topic!=\"__consumer_offsets\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka\",topic!=\"\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In per Topic",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka\", topic=~\"docker|demoemo|kafka1|tag1|tag2|tag4|tag3\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Out per Topic",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka\", topic=~\"docker|demoemo|kafka1|tag1|tag2\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Messages in per Topic",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_server_brokertopicmetrics_messagesin_total{instance=~\"kafka1:9101|kafka2:9102\", topic=~\"docker|demoemo|kafka1|tag1|tag2|tag4|tag3\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topic Replicas Count",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(topic) (kafka_cluster_partition_replicascount{job=\"kafka\" , topic!=\"__consumer_offsets\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "AMS Dashboard", "type": "stat", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 33 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } }
 ]
}